/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolSystemManagement.manager.user;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import org.json.JSONObject;
import schoolSystemManagement.common.SelfUserEdit;
import schoolSystemManagement.dto.UserData;
import schoolSystemManagement.file.JsonFile;

/**
 * @author admin
 */
public class UserManagerHome extends javax.swing.JFrame {

    // 테스트를 위한 기본 값 설정입니다.
    public String userManagerName = "김영진";
    public String userManagerId = "S-027";

    // 전체적으로 사용하기 위해 파일을 불러오는 부분입니다.
    JsonFile usersFile = new JsonFile("user_data.json", "user_data.json");
    JsonFile coursesFile = new JsonFile("course_data.json", "course_data.json");


    /**
     * 기본 생성자 입니다.
     */
    public UserManagerHome() {
        initComponents();
        // 크기 조정 완전 금지
        setResizable(false);
        setTitle("수업 담당자 메뉴");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * 부모 프레임으로 부터 이름과 아이디를 전달받아 사용하는 생성자 입니다.
     *
     * @param userManagerName
     * @param userManagerId
     */
    public UserManagerHome(String userManagerName, String userManagerId) {
        this.userManagerName = userManagerName;
        this.userManagerId = userManagerId;
        initComponents();
        // 크기 조정 완전 금지
        setResizable(false);
        setTitle("수업 담당자 메뉴");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        userManagementButton = new javax.swing.JButton();
        userManagerEditProfil = new javax.swing.JButton();
        courseManagerMajorFrame = new javax.swing.JTextField();
        roleLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        userManagerIdFrame = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        userManagerNameFrame = new javax.swing.JTextField();
        usersLabel = new javax.swing.JLabel();
        usersScrollPane = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        titleLabel = new javax.swing.JLabel();
        reData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        userManagementButton.setBackground(new java.awt.Color(255, 255, 255));
        userManagementButton.setText("사용자 관리");
        userManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementButtonActionPerformed(evt);
            }
        });

        userManagerEditProfil.setBackground(new java.awt.Color(255, 255, 255));
        userManagerEditProfil.setText("내 정보 수정");
        userManagerEditProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagerEditProfilActionPerformed(evt);
            }
        });

        courseManagerMajorFrame.setEditable(false);
        courseManagerMajorFrame.setBackground(new java.awt.Color(255, 255, 255));
        courseManagerMajorFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseManagerMajorFrame.setText("학사 담당자");
        courseManagerMajorFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        courseManagerMajorFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseManagerMajorFrameActionPerformed(evt);
            }
        });

        roleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roleLabel.setText("직책");

        idLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        idLabel.setText("아이디");

        userManagerIdFrame.setEditable(false);
        userManagerIdFrame.setBackground(new java.awt.Color(255, 255, 255));
        userManagerIdFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userManagerIdFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        userManagerIdFrame.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                userManagerIdFrameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("이름");

        userManagerNameFrame.setEditable(false);
        userManagerNameFrame.setBackground(new java.awt.Color(255, 255, 255));
        userManagerNameFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userManagerNameFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        userManagerNameFrame.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                userManagerNameFrameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        usersLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usersLabel.setText("가입 된 모든 사용자");

        usersTable.setBackground(new java.awt.Color(255, 255, 255));
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usersTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                usersTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        usersScrollPane.setViewportView(usersTable);

        titleLabel.setFont(new java.awt.Font("HY견고딕", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("학사 담당자 메뉴");
        titleLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        reData.setBackground(new java.awt.Color(255, 255, 255));
        reData.setText("새로고침");
        reData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseManagerMajorFrame)
                    .addComponent(userManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerEditProfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(roleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerIdFrame)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerNameFrame)
                    .addComponent(usersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reData)
                .addGap(4, 4, 4)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userManagerNameFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userManagerIdFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseManagerMajorFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(userManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userManagerEditProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementButtonActionPerformed
        // 해당 방식으로 추가할겁니다.
        UserEditData userEditDataManagementScreen = new UserEditData();

        // 기존 창 기준으로 우측에 위치 설정
        userEditDataManagementScreen.setLocation(this.getX() + this.getWidth(), this.getY());

        // 새 창을 표시
        userEditDataManagementScreen.setVisible(true);
    }//GEN-LAST:event_userManagementButtonActionPerformed

    private void userManagerEditProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagerEditProfilActionPerformed
        // 내 정보 수정 버튼을 눌렀을 때 이벤트
        SelfUserEdit selfUserEditManagementScreen = new SelfUserEdit(userManagerName, userManagerId);

        // 기존 창 기준으로 우측에 위치 설정
        selfUserEditManagementScreen.setLocation(this.getX() + this.getWidth(), this.getY());

        // 새 창을 표시
        selfUserEditManagementScreen.setVisible(true);
    }//GEN-LAST:event_userManagerEditProfilActionPerformed

    private void courseManagerMajorFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseManagerMajorFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseManagerMajorFrameActionPerformed

    private void userManagerNameFrameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_userManagerNameFrameAncestorAdded
        // 이름 불러오기
        userManagerNameFrame.setText(userManagerName);
    }//GEN-LAST:event_userManagerNameFrameAncestorAdded

    private void userManagerIdFrameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_userManagerIdFrameAncestorAdded
        // 아이디 불러오기
        userManagerIdFrame.setText(userManagerId);
    }//GEN-LAST:event_userManagerIdFrameAncestorAdded

    private void usersTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usersTableAncestorAdded
        // JSON 데이터 가져오기 (테스트용 예제 JSON)
        JSONObject filteredObjects = usersFile.getJsonObject(); // 이미 정의된 JSON 데이터 객체

        ArrayList<UserData> usersDataList = new ArrayList<>();

        // JSON 데이터를 파싱하여 DTO 객체로 변환
        for (String key : filteredObjects.keySet()) {
            JSONObject course = filteredObjects.getJSONObject(key);

            // 속성 추출
            String name = course.optString("name", "N/A");
            String userId = course.optString("userId", "N/A");
            String number = course.optString("number", "N/A");
            String major = course.optString("major", "N/A");
            String userType = course.optString("userType", "N/A");

            // DTO 객체로 저장
            UserData usersDTO = new UserData(name, userId, number, major, userType);
            usersDataList.add(usersDTO);
        }

        // JTable 테이블 모델 생성
        String[] columnNames = {"이름", "아이디", "전공", "직책"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

        // 데이터를 테이블 모델에 추가
        for (UserData user : usersDataList) {
            Object[] rowData = {
                    user.getName(),
                    user.getUserId(),
                    user.getMajor(),
                    user.getUserType()
            };
            tableModel.addRow(rowData);
        }

        // jTable1에 모델 설정
        usersTable.setModel(tableModel);

        // 읽기 전용 설정
        usersTable.setEnabled(false);
    }//GEN-LAST:event_usersTableAncestorAdded

    private void reDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reDataActionPerformed
        usersFile = new JsonFile("user_data.json", "user_data.json");
        JSONObject filteredObjects = usersFile.getJsonObject(); // 이미 정의된 JSON 데이터 객체

        ArrayList<UserData> usersDataList = new ArrayList<>();

        // JSON 데이터를 파싱하여 DTO 객체로 변환
        for (String key : filteredObjects.keySet()) {

            // 파일 내용 업데이트
            usersFile = new JsonFile("user_data.json", "user_data.json");

            JSONObject userObject = filteredObjects.getJSONObject(key); // 'course' 대신 'userObject'로 변경

            // 속성 추출
            String name = userObject.optString("name", "N/A");
            String userId = userObject.optString("userId", "N/A");
            String number = userObject.optString("number", "N/A");
            String major = userObject.optString("major", "N/A");
            String userType = userObject.optString("userType", "N/A");

            // DTO 객체로 저장
            UserData userData = new UserData(name, userId, number, major, userType);
            usersDataList.add(userData);
        }

        // JTable 테이블 모델 생성 및 초기화
        String[] columnNames = {"이름", "아이디", "전공", "직책"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0); // 모델 초기화

        // 데이터를 테이블 모델에 추가
        for (UserData user : usersDataList) {
            Object[] rowData = {
                    user.getName(),
                    user.getUserId(),
                    user.getMajor(),
                    user.getUserType()
            };
            tableModel.addRow(rowData);
        }

        // jTable1에 모델 설정 및 초기화
        usersTable.setModel(tableModel);
        usersTable.setEnabled(false); // 읽기 전용 설정
    }//GEN-LAST:event_reDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseManagerMajorFrame;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton reData;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton userManagementButton;
    private javax.swing.JButton userManagerEditProfil;
    private javax.swing.JTextField userManagerIdFrame;
    private javax.swing.JTextField userManagerNameFrame;
    private javax.swing.JLabel usersLabel;
    private javax.swing.JScrollPane usersScrollPane;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
