/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schoolSystemManagement.manager.user;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import org.json.JSONObject;
import schoolSystemManagement.dto.UserData;
import schoolSystemManagement.file.JsonFile;

/**
 *
 * @author admin
 */
public class UserManagerHome extends javax.swing.JFrame {
    
    public String userManagerName = "김영진";
    public String userManagerId = "S-027";
    JsonFile usersFile = new JsonFile("user_data.json", "user_data.json");
    JsonFile coursesFile = new JsonFile("course_data.json", "course_data.json");

    /**
     * Creates new form StudentHome
     */
    public UserManagerHome() {
        initComponents();
        // 크기 조정 완전 금지
        setResizable(false);
        setTitle("수업 담당자 메뉴");
    }
    public UserManagerHome(String userManagerName, String userManagerId) {
        this.userManagerName = userManagerName;
        this.userManagerId = userManagerId;
        initComponents();
        // 크기 조정 완전 금지
        setResizable(false);
        setTitle("수업 담당자 메뉴");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userManagementButton = new javax.swing.JButton();
        userManagerEditProfil = new javax.swing.JButton();
        courseManagerMajorFrame = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userManagerIdFrame = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userManagerNameFrame = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        userManagementButton.setBackground(new java.awt.Color(255, 255, 255));
        userManagementButton.setText("사용자 관리");
        userManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementButtonActionPerformed(evt);
            }
        });

        userManagerEditProfil.setBackground(new java.awt.Color(255, 255, 255));
        userManagerEditProfil.setText("내 정보 수정");
        userManagerEditProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagerEditProfilActionPerformed(evt);
            }
        });

        courseManagerMajorFrame.setEditable(false);
        courseManagerMajorFrame.setBackground(new java.awt.Color(255, 255, 255));
        courseManagerMajorFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        courseManagerMajorFrame.setText("학사 담당자");
        courseManagerMajorFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        courseManagerMajorFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseManagerMajorFrameActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("직책");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("아이디");

        userManagerIdFrame.setEditable(false);
        userManagerIdFrame.setBackground(new java.awt.Color(255, 255, 255));
        userManagerIdFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userManagerIdFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        userManagerIdFrame.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                userManagerIdFrameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("이름");

        userManagerNameFrame.setEditable(false);
        userManagerNameFrame.setBackground(new java.awt.Color(255, 255, 255));
        userManagerNameFrame.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userManagerNameFrame.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        userManagerNameFrame.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                userManagerNameFrameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("가입 된 모든 사용자");

        jLabel1.setFont(new java.awt.Font("HY견고딕", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("수업 담당자 메뉴");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(courseManagerMajorFrame)
                    .addComponent(userManagementButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerEditProfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerIdFrame)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userManagerNameFrame)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userManagerNameFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userManagerIdFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseManagerMajorFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(userManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userManagerEditProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementButtonActionPerformed
        // 해당 방식으로 추가할겁니다.
        //ChargeTuitionFeeSystemForManager chargeTuitionFeeManagementScreen = new ChargeTuitionFeeSystemForManager(courseManagerName, courseManagerId);

        // 기존 창 기준으로 우측에 위치 설정
        //chargeTuitionFeeManagementScreen.setLocation(this.getX() + this.getWidth(), this.getY());

        // 새 창을 표시
        //chargeTuitionFeeManagementScreen.setVisible(true);
    }//GEN-LAST:event_userManagementButtonActionPerformed

    private void userManagerEditProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagerEditProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userManagerEditProfilActionPerformed

    private void courseManagerMajorFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseManagerMajorFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseManagerMajorFrameActionPerformed

    private void userManagerNameFrameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_userManagerNameFrameAncestorAdded
        // 이름 불러오기
        userManagerNameFrame.setText(userManagerName);
    }//GEN-LAST:event_userManagerNameFrameAncestorAdded

    private void userManagerIdFrameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_userManagerIdFrameAncestorAdded
        // 아이디 불러오기
        userManagerIdFrame.setText(userManagerId);
    }//GEN-LAST:event_userManagerIdFrameAncestorAdded

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // JSON 데이터 가져오기 (테스트용 예제 JSON)
    JSONObject filteredObjects = usersFile.getJsonObject(); // 이미 정의된 JSON 데이터 객체

    ArrayList<UserData> usersDataList = new ArrayList<>();

    // JSON 데이터를 파싱하여 DTO 객체로 변환
    for (String key : filteredObjects.keySet()) {
        JSONObject course = filteredObjects.getJSONObject(key);

        // 속성 추출
        String name = course.optString("name", "N/A");
        String userId = course.optString("userId", "N/A");
        String number = course.optString("number", "N/A");
        String major = course.optString("major", "N/A");
        String userType = course.optString("userType", "N/A");

        // DTO 객체로 저장
        UserData usersDTO = new UserData(name, userId, number, major, userType);
        usersDataList.add(usersDTO);
        }

        // JTable 테이블 모델 생성
        String[] columnNames = {"이름", "아이디", "전공", "직책"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

        // 데이터를 테이블 모델에 추가
        for (UserData user : usersDataList) {
            Object[] rowData = {
                user.getName(),
                user.getUserId(),
                user.getMajor(),
                user.getUserType()
            };
            tableModel.addRow(rowData);
        }

        // jTable1에 모델 설정
        jTable1.setModel(tableModel);

        // 읽기 전용 설정
        jTable1.setEnabled(false);
    }//GEN-LAST:event_jTable1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField courseManagerMajorFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton userManagementButton;
    private javax.swing.JButton userManagerEditProfil;
    private javax.swing.JTextField userManagerIdFrame;
    private javax.swing.JTextField userManagerNameFrame;
    // End of variables declaration//GEN-END:variables
}
