/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schoolSystemManagement;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
/**
 *
 * @author limmi
 */
public class Edit extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    // 데이터를 저장할 HashMap (외부에서 주입된 데이터를 사용한다고 가정)
    private HashMap<String, String> dataMap;

    /**
     * Creates new form Edit
     */
    public Edit(HashMap<String, String> dataMap) {
        this.dataMap = dataMap; // 데이터 맵을 외부에서 전달받아 초기화
        initComponents();
        setupFields(); // 필드에 기존 데이터 설정
        setupActions(); // 버튼 동작 설정
    }
    // 필드에 데이터를 설정하는 메서드
    private void setupFields() {
        // HashMap에서 데이터를 가져와서 각 필드에 설정
        if (dataMap != null) {
            idField.setText(dataMap.getOrDefault("id", ""));
            idField.setEditable(false); // 학번/교수 번호는 수정 불가능하도록 설정
            NameField.setText(dataMap.getOrDefault("name", ""));
            deptBox.setSelectedItem(dataMap.getOrDefault("dept", ""));
            ssnField.setText(dataMap.getOrDefault("ssn", ""));
        }
    }
    private void setupActions() {
        // 수정 버튼 클릭 시 동작
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // 변경된 데이터 가져오기
                String newName = NameField.getText();
                String newDept = (String) deptBox.getSelectedItem();
                String newSsn = ssnField.getText();

                // 유효성 검사
                if (newName.isEmpty() || newSsn.isEmpty()) {
                    JOptionPane.showMessageDialog(Edit.this, "이름과 주민번호는 필수 입력 사항입니다.", "오류", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // 데이터 맵에 수정된 데이터 반영
                dataMap.put("name", newName);
                dataMap.put("dept", newDept);
                dataMap.put("ssn", newSsn);

                // 수정 완료 메시지
                JOptionPane.showMessageDialog(Edit.this, "정보가 성공적으로 수정되었습니다.", "성공", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("수정된 데이터: " + dataMap); // 콘솔에 수정된 데이터 출력
            }
        });

        // 취소 버튼 클릭 시 동작
        jButton2.addActionListener(e -> {
            // 취소 시 기존 데이터로 필드를 다시 설정하여 변경을 되돌림
            setupFields();
            JOptionPane.showMessageDialog(Edit.this, "수정이 취소되었습니다.", "알림", JOptionPane.INFORMATION_MESSAGE);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deptBox = new javax.swing.JComboBox<>();
        NameField = new javax.swing.JTextField();
        ssnField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        jLabel1.setText("정보 수정");

        jLabel2.setText("이름");

        jLabel3.setText("학과");

        jLabel4.setText("주민번호");

        deptBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "전산학과", "전자공학과", "화학공학과", "기계공학과", "항공우주공학과" }));

        jButton1.setText("수정");

        jButton2.setText("취소");

        jLabel5.setText("학번/교수번호");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(deptBox, 0, 150, Short.MAX_VALUE)
                            .addComponent(NameField)
                            .addComponent(ssnField)
                            .addComponent(idField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ssnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameField;
    private javax.swing.JComboBox<String> deptBox;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField ssnField;
    // End of variables declaration//GEN-END:variables
}
