/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package schoolSystemManagement;

import schoolSystemManagement.course.management.*;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import com.google.gson.internal.LinkedTreeMap;
import org.json.JSONObject;
import java.util.List;
import java.io.*;
import java.lang.reflect.Type;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author limmi
 */
public class Login extends javax.swing.JPanel {

    // 주민번호 키를 String으로 처리
    private HashMap<String, HashMap<String, String>> userMap = new HashMap<>();
    private static final String FILE_PATH = "user_data.json"; // JSON 파일 경로
    private final Gson gson = new Gson(); // GSON 객체

    public Login() {
        initComponents();
        loadFromJson(); // 프로그램 시작 시 사용자 데이터 로드
    }

    private void loadFromJson() {
        try (Reader reader = new FileReader(FILE_PATH)) {
            // JSON 데이터를 읽어오는 Map 타입
            Type type = new TypeToken<HashMap<String, Map<String, Object>>>() {}.getType();
            Map<String, Map<String, Object>> rawMap = gson.fromJson(reader, type);

            userMap = new HashMap<>();

            if (rawMap != null) {
                for (Map.Entry<String, Map<String, Object>> entry : rawMap.entrySet()) {
                    String key = entry.getKey();
                    Map<String, Object> userData = entry.getValue();

                    // 원본 그대로 userMap에 저장
                    HashMap<String, String> processedUserData = new HashMap<>();
                    for (Map.Entry<String, Object> userEntry : userData.entrySet()) {
                        processedUserData.put(userEntry.getKey(), userEntry.getValue().toString());  // 값 그대로 저장
                    }

                    userMap.put(key, processedUserData);
                }
            }

            System.out.println("JSON 파일에서 데이터가 로드되었습니다.");
            userMap.forEach((key, value) -> System.out.println("키: " + key + ", 값: " + value));
        } catch (FileNotFoundException e) {
            System.out.println("JSON 파일이 존재하지 않습니다. 새로 생성해야 합니다.");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "데이터를 로드하는 중 오류가 발생했습니다.");
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();

        loginButton.setText("로그인");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("로그인");

        jLabel2.setText("학번/교수 번호");

        jLabel3.setText("비밀번호");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(loginButton)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(loginButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        try {
            String idInput = idField.getText().trim(); // 사용자 ID
            String passwordInput = passwordField.getText().trim(); // 비밀번호

            if (idInput.isEmpty() || passwordInput.isEmpty()) {
                JOptionPane.showMessageDialog(this, "아이디와 비밀번호를 입력해주세요!");
                return;
            }

            // 로그인 검증
            HashMap<String, String> loggedInUser = null;

            // userMap을 순회하여 사용자가 입력한 아이디와 비밀번호 일치 여부 체크
            for (Map.Entry<String, HashMap<String, String>> entry : userMap.entrySet()) {
                HashMap<String, String> userData = entry.getValue();

                String userId = userData.get("userId").trim();  // userId에서 불필요한 공백 제거
                String userPassword = userData.get("number").trim();  // number에서 불필요한 공백 제거

                // 디버깅 출력을 추가하여 확인
                System.out.println("입력된 ID: " + idInput + ", 입력된 비밀번호: " + passwordInput);
                System.out.println("비교할 ID: " + userId + ", 비교할 비밀번호: " + userPassword);

                // 아이디(userId)와 비밀번호(number)가 일치하는지 비교
                if (userId != null && userPassword != null
                        && userId.equals(idInput)
                        && userPassword.equals(passwordInput)) {
                    loggedInUser = userData; // 로그인한 사용자 정보 저장
                    JOptionPane.showMessageDialog(this, "로그인 성공! " + userData.get("name") + "님 환영합니다.");
                    break;
                }
            }

            // 일치하는 사용자 정보가 없으면 로그인 실패 처리
            if (loggedInUser == null) {
                JOptionPane.showMessageDialog(this, "아이디 또는 비밀번호가 일치하지 않습니다.");
                return;
            }

            // 사용자 유형에 따른 화면 이동
            String userType = loggedInUser.get("userType");

            if ("학생".equals(userType)) {
                CourseManagementSystemForStudents studentScreen = new CourseManagementSystemForStudents(loggedInUser.get("userId"), loggedInUser.get("name"));
                studentScreen.setVisible(true);
                this.setVisible(false);
            } else if ("교수".equals(userType)) {
                CourseManagementSystemForProfessor professorScreen = new CourseManagementSystemForProfessor(loggedInUser.get("userId"), loggedInUser.get("name"));
                professorScreen.setVisible(true);
                this.setVisible(false);
            } else if ("수업 담당자".equals(userType)) {
                // 수업 담당자 화면 처리
                CourseManagementSystemForManager classInstructorScreen = new CourseManagementSystemForManager(loggedInUser.get("userId"), loggedInUser.get("userId"));
                classInstructorScreen.setVisible(true);
                this.setVisible(false);
            } else if ("학사 담당자".equals(userType)) {
                // 학사 담당자 화면 처리
                CourseManagementSystemForManager adminScreen = new CourseManagementSystemForManager(loggedInUser.get("userId"), loggedInUser.get("userId"));
                adminScreen.setVisible(true);
                this.setVisible(false);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "로그인 처리 중 오류가 발생했습니다.");
        }

    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField passwordField;
    // End of variables declaration//GEN-END:variables
}
